name: Build and Test ASP.NET Core

on:
  push:
    branches:
      - main  # Run when you push to the main branch.
  pull_request:
    branches:
      - main  # Run when you create a pull request to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies that the job will run on an Ubuntu server.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the code from your repository.

      - name: Set up .NET
        uses: actions/setup-dotnet@v1  # This sets up the .NET SDK.
        with:
          dotnet-version: '7.0'  # Use your .NET version here.

      - name: Restore dependencies
        run: dotnet restore  # Restore the project's dependencies.

      - name: Build project
        run: dotnet build --configuration Release  # Build the project in release mode.

      - name: Run tests
        run: dotnet test --configuration Release --no-restore  # Run tests to check if everything works.

